name: Release Build

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["x86_64", "aarch64", "armv7l"]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup CentOS 7 build environment
      run: |
        docker run --rm -v "$(pwd):/build" centos:7.6.1810 bash -c "
          rm -f /etc/yum.repos.d/CentOS-*.repo &&
          cat <<'EOF' > /etc/yum.repos.d/C7.6.1810.repo
        [C7.6.1810-base]
        name=CentOS-7.6.1810 - Base
        baseurl=https://mirrors.aliyun.com/centos-vault/7.6.1810/os/x86_64/$basearch
        gpgcheck=0
        gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
        enabled=1
        [C7.6.1810-updates]
        name=CentOS-7.6.1810 - Updates
        baseurl=https://mirrors.aliyun.com/centos-vault/7.6.1810/updates/x86_64/$basearch
        gpgcheck=0
        gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
        enabled=1
        [C7.6.1810-extras]
        name=CentOS-7.6.1810 - Extras
        baseurl=https://mirrors.aliyun.com/centos-vault/7.6.1810/extras/x86_64/$basearch
        gpgcheck=0
        gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
        enabled=1
        [C7.6.1810-centosplus]
        name=CentOS-7.6.1810 - CentOSPlus
        baseurl=https://mirrors.aliyun.com/centos-vault/7.6.1810/centosplus/x86_64/$basearch
        gpgcheck=0
        gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
        enabled=1
        [C7.6.1810-fasttrack]
        name=CentOS-7.6.1810 - Fasttrack
        baseurl=https://mirrors.aliyun.com/centos-vault/7.6.1810/fasttrack/x86_64/$basearch
        gpgcheck=0
        gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
        enabled=1
        EOF
        cat /etc/yum.repos.d/C7.6.1810.repo &&
        yum install -y gcc glibc-static make &&
        cd /build &&
        make ARCH=${{ matrix.arch }} CC=gcc CFLAGS='-Wall -Werror -g'
        "

    - name: Collect artifacts
      run: |
        mkdir -p artifacts
        mv su-exec artifacts/su-exec-${{ matrix.arch }}

    - name: Upload release assets
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
